Added again make command for integration test in workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,13 +60,13 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y docker-compose
 
-      # - name: Running integration tests
-      #   run: make test-integration
-      #   continue-on-error: false
-      - name: Build and run integration tests
-        run: |
-          docker-compose -p tests -f docker/test-integration/docker-compose.yml up --build --abort-on-container-exit --exit-code-from tester || (echo "Tests failed. Showing logs:" && docker-compose -p tests -f docker/test-integration/docker-compose.yml logs)
+      - name: Running integration tests
+        run: make test-integration
+        continue-on-error: false
+      # - name: Build and run integration tests
+      #   run: |
+      #     docker-compose -p tests -f docker/test-integration/docker-compose.yml up --build --abort-on-container-exit --exit-code-from tester || (echo "Tests failed. Showing logs:" && docker-compose -p tests -f docker/test-integration/docker-compose.yml logs)
 
-      - name: Clean up
-        if: always()
-        run: docker-compose -p tests -f docker/test-integration/docker-compose.yml down
+      # - name: Clean up
+      #   if: always()
+      #   run: docker-compose -p tests -f docker/test-integration/docker-compose.yml down
